name: CI to Docker Hub

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    
steps:
  
  - name: Echo AAA
    run: echo Hello World.
    
  - name: Echo BBB
    run: echo ${{ secrets.DOCKER_HUB_USERNAME }}
